name: Set up Workspace
description: "Checks out repository, installs correct version of node and npm dependencies."
inputs:
  do_checkout:
    description: "Run actions/checkout inside the composite"
    default: "true"
  ref:
    description: "Ref to checkout (optional)"
    required: false
  repository:
    description: "Repo to checkout (optional)"
    required: false
runs:
  using: composite
  steps:
    - name: Checkout
      if: ${{ inputs.do_checkout == 'true' }}
      uses: actions/checkout@v4

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 9
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: "pnpm"

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --strict-peer-dependencies

    - name: Install Global Packages
      shell: bash
      run: pnpm add -g gulp prettier typescript
    - name: Install Cypress Binary
      shell: bash
      run: pnpm --filter @ucla-library-monorepo/ucla-library-website-components exec cypress install

    - name: Cache Cypress Binary
      uses: actions/cache@v3
      with:
        path: ~/.cache/Cypress
        key: cypress-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          cypress-${{ runner.os }}-
